language: node_js
node_js:
  - "6.7"
services:
  - redis-server
sudo: required
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
install:
  - npm install;
  - npm install travis-github-lint-status;
script:
  - if [[ "$SAUCE_USERNAME" == "" ]]; then
      eval $CMD;
    elseif [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      mv config/config-ci.json config/config.json && npm run regression-test;
    fi
env:
  - CMD="./node_modules/travis-github-lint-status/index.js"
  - CMD="npm run test && bash <(curl -s https://codecov.io/bash)" TB_API_KEY=123 TB_API_SECRET=123
  - SAUCE_USERNAME=opentok
addons:
  firefox: "latest"
